name: proyectomovilesii
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.12.1
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  geolocator: ^14.0.0
  intl: ^0.20.2
  uuid: ^4.5.1
  permission_handler: ^12.0.0+1
  google_maps_webservice: ^0.0.18
  flutter_polyline_points: ^1.0.0
  geocoding: ^2.0.5
  flutter_map: ^4.0.0
  flutter_map_heatmap: ^0.0.5
  latlong2: ^0.8.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
